apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysqldb
  namespace: argocd
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: mysqldb-secret
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: mysqldb-secret
