apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: skywalking
  namespace: argocd
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: skywalking-secret
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: skywalking-secret
