apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    istio-injection: enabled

---

apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    istio-injection: enabled