
name: Details Service Build, Push and Deploy

on:
  workflow_dispatch:

  push:
    paths:
      - 'bookinfo_app/src/details/**'

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 970547342192.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: my-ecr-repo

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get short SHA
        id: get-sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build and Push Docker Image to ECR
        env:
          IMAGE_TAG: details-${{ steps.get-sha.outputs.sha }}
        run: |
          IMAGE_URI=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          docker build -t $IMAGE_URI ./bookinfo_app/src/details/
          docker push $IMAGE_URI

      - name: Update Kubernetes Deployment Image
        env:
          IMAGE_TAG: details-${{ steps.get-sha.outputs.sha }}
        run: |
          DEPLOYMENT_FILE="manifests/kubernetes/details/deployment_details.yaml"
          IMAGE_URI="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG"

          if grep -q "$IMAGE_URI" "$DEPLOYMENT_FILE"; then
            echo "Image already up to date in $DEPLOYMENT_FILE"
          else
            sed -i "s|image: .*|image: $IMAGE_URI|" "$DEPLOYMENT_FILE"

            git config user.email "action@github.com"
            git config user.name "GitHub Action"
            git add "$DEPLOYMENT_FILE"
            git commit -m "Update details deployment image to $IMAGE_URI"
            git push
          fi
